### PR TITLE
skewT required arguments

### PR DESCRIPTION
**Pull request by brendan-ryan**
This change adds a check that is specific to skewT diagrams.
If --max_plev or --sites arguments are missing, parser throws an error message indicating which required argument is missing and exits the application without dumping further exception messages to user.

### CODE REVIEW

**Review by Brian-Jamison — APPROVED** [review]
Looks good to me!  Thanks for handling this.

**Review by cshartsough — APPROVED** [review]
good  job.  Congrats  on you first PR :-)

**Review by christinaholtNOAA — APPROVED** [review]
Very nice! A useful contribution for our users.

I pushed the button to run the autotests and they pass. It's ready to merge. :)

**Comment by brendan-ryan** [comment]
Super! Thanks, all.

**Pull request merged**
